# Generated by Django 4.2.6 on 2023-11-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=25)),
                ('contrasena', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=70)),
            ],
        ),
    ]
